In [1]:
import numpy as np

# Algebra linear no NP
## multiplicação matricial / produto escalar
> np.dot(array1, array2)
- quando as 2 arrays são de 1D, ele retorna o produto escalar
- quando uma delas é pelo menos de 2D, ele retorna a multiplicação matricial

In [9]:
X = np.array([[1, 2, 3], [4, 5, 6]])
Y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(X.shape)
print(Y.shape)
print("multiplicação matricial:")
print(np.dot(X, Y))

(2, 3)
(3, 3)
multiplicação matricial:
[[ 66  72  78]
 [156 171 186]]


In [6]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
print(f"produto escalar: {np.dot(X, Y)}")

produto escalar: 32


> OBS: @ e np.matmul tambem faz mult matricial

In [13]:
X = np.array([[1, 2, 3], [4, 5, 6]])
Y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(X @ Y)
print(np.matmul(X, Y))

[[ 66  72  78]
 [156 171 186]]
[[ 66  72  78]
 [156 171 186]]


## transposta
> array.T
- troca linhas por colunas

In [17]:
print(X)
print(X.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## determinante
> np.linalg.det()

In [31]:
rng = np.random.default_rng()
A = rng.integers(low=1, high=20, size=(5, 5), endpoint=True)
print(A)
print(np.linalg.det(A))

[[ 8  6 19  6  8]
 [14 10 13  1 15]
 [15  8 16  7 11]
 [ 6  5 18  3 10]
 [ 7  8 13  1  9]]
211.99999999999866


## Inversa
> np.linalg.inv()

In [34]:
A_inv = np.linalg.inv(A)
print(A_inv)
## testando a matriz identidade
print(A @ A_inv)

[[ 10.0754717    6.35849057  -6.41509434  -5.39622642  -5.71698113]
 [ -5.58962264  -3.61320755   3.61792453   2.78301887   3.47641509]
 [  5.86792453   3.62264151  -3.77358491  -3.05660377  -3.24528302]
 [-13.07075472  -8.27358491   8.51415094   6.93396226   7.29716981]
 [ -9.89150943  -6.04716981   6.27830189   5.36792453   5.34433962]]
[[ 1.00000000e+00 -7.10542736e-15  0.00000000e+00  0.00000000e+00
  -7.10542736e-15]
 [ 1.24344979e-14  1.00000000e+00 -1.50990331e-14  8.88178420e-15
  -2.66453526e-15]
 [ 1.95399252e-14 -2.66453526e-15  1.00000000e+00  8.88178420e-15
  -1.33226763e-14]
 [ 1.77635684e-14 -8.88178420e-15  8.88178420e-15  1.00000000e+00
   5.32907052e-15]
 [ 1.77635684e-15 -8.88178420e-16 -6.21724894e-15 -1.77635684e-15
   1.00000000e+00]]


## Autovalores e autovetores
> np.linalg.eig(A)
- autovetor -> direção que não muda mesmo quando a matriz age
- autovalor -> o quão essa direção aumenta ou diminui

In [36]:
autovalores, autovetores = np.linalg.eig(A)
autovalores

array([48.8003363 ,  5.20430913, -5.88934351,  0.06500771, -2.18030965])

In [37]:
autovetores

array([[-0.44589761,  0.43550257, -0.40431186,  0.48701916,  0.33076737],
       [-0.48646811, -0.69080909,  0.36469145, -0.26855067, -0.71588445],
       [-0.52754055,  0.31998399,  0.51847273,  0.27827641,  0.15367409],
       [-0.39712362,  0.10080234, -0.5043496 , -0.62151359, -0.56837479],
       [-0.35849393, -0.46964822, -0.42467585, -0.47641995,  0.17730418]])

## Norma
> np.linalg.norm(array, ord=num_da_norma)
- mede o tamanho o comprimento de um vetor
- o paramentro "ord" dita qual norma será usada pra medir
  - exemplo: ord=1 é norma de Manhattan, ord=2 é norma Euclidiana (mais usado)

In [40]:
B = rng.integers(low=1, high=11, size=(2, 2))
B

array([[5, 6],
       [3, 3]])

In [41]:
B_norma = np.linalg.norm(B, ord=2)
print(f'distância euclidiana do vetor B: {B_norma}')

distância euclidiana do vetor B: 8.88177410130521
