# Atividades
1. Crie um array com os números de 1 a 10.

- Calcule a soma de todos os elementos.

- Calcule a média.

In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr_soma = np.sum(arr)
arr_media = np.mean(arr)
print(f"Soma de todos os elementos: {arr_soma}")
print(f"Média do array: {arr_media}")

Soma de todos os elementos: 55
Média do array: 5.5


2. Gere um array de 20 números aleatórios inteiros entre 1 e 100.

- Descubra o valor máximo e mínimo.

- Descubra os índices do máximo e do mínimo.

In [8]:
rng = np.random.default_rng()
arr = rng.integers(low=1, high=100, size=20, endpoint=True)
arr

array([89, 36, 88,  5, 67, 69, 95,  7, 58, 56, 66, 77, 45, 16, 41, 77, 52,
        4, 79, 78])

In [9]:
arr_minimo = np.min(arr)
arr_maximo = np.max(arr)
print(f'valor minimo no array: {arr_minimo}')
print(f'valor maximo no array: {arr_maximo}')

valor minimo no array: 4
valor maximo no array: 95


In [10]:
arr_imax = np.argmax(arr)
arr_imin = np.argmin(arr)
print(f'indice do valor maximo: {arr_imax}')
print(f'indice do valor minimo: {arr_imin}')

indice do valor maximo: 6
indice do valor minimo: 17


3. Considere o array:

> arr = np.array([5, 7, 8, 7, 10, 7, 3])


- Qual o índice do maior valor?

- Qual o índice do menor valor?

- Se houver repetição de valores (como os vários 7), qual índice argmax() e argmin() retornam?

In [20]:
arr = np.array([5, 7, 8, 7, 10, 7, 3])
arr

array([ 5,  7,  8,  7, 10,  7,  3])

In [22]:
arr_imax = np.argmax(arr)
arr_imin = np.argmin(arr)
print(f'indice de maior valor: {arr_imax}')
print(f'indice de menor valor: {arr_imin}')
print(f'caso fossem numeros repetidos no argmax ou argmin, ele retornaria o indice que primeiro aparece o num repetido')

indice de maior valor: 4
indice de menor valor: 6
caso fossem numeros repetidos no argmax ou argmin, ele retornaria o indice que primeiro aparece o num repetido


In [24]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr_media_linhas = np.mean(arr, axis=1)
arr_media_linhas

array([ 2.5,  6.5, 10.5])

In [26]:
arr_media_col = np.mean(arr, axis=0)
arr_media_col

array([5., 6., 7., 8.])

In [27]:
arr = rng.integers(low=0, high=50, size=(5, 5), endpoint=True)
arr

array([[10,  6, 16, 18, 26],
       [20, 25, 11, 26, 38],
       [ 5, 35, 35, 49, 22],
       [41,  5, 39, 25, 29],
       [42, 13,  4, 34, 44]])

In [30]:
arr_desviop = np.std(arr)
print(f'desvio padrão do array: {arr_desviop}')

desvio padrão do array: 13.379147954933451


In [33]:
arr_valor_max = np.max(arr)
arr_indice_max = np.argmax(arr)
print(f"valor maximodo array: {arr_valor_max}.\nSeu índice: {arr_indice_max}")
print("Posição real: (3, 4)")

valor maximodo array: 49.
Seu índice: 13
Posição real: (3, 4)


In [37]:
arr = rng.random(100)
arr

array([0.01897946, 0.37839226, 0.25926291, 0.68137244, 0.99887494,
       0.56501425, 0.47835837, 0.62772428, 0.13719208, 0.26321788,
       0.17523914, 0.13157764, 0.29261069, 0.19754811, 0.03268041,
       0.92039772, 0.91021594, 0.30533007, 0.2408917 , 0.92949153,
       0.10401715, 0.0675216 , 0.46666997, 0.10196101, 0.08951844,
       0.79361113, 0.92297929, 0.85745031, 0.22424713, 0.10533613,
       0.01712698, 0.22199171, 0.10233635, 0.77496247, 0.94387934,
       0.1790782 , 0.64871155, 0.32311197, 0.43314262, 0.51992338,
       0.73737797, 0.67960101, 0.62247893, 0.83238506, 0.32717309,
       0.70111922, 0.93296825, 0.96835719, 0.38837959, 0.25295879,
       0.45497147, 0.23028054, 0.7713401 , 0.20607023, 0.84419718,
       0.94162074, 0.82844492, 0.34423941, 0.19579543, 0.94624619,
       0.9398509 , 0.70320655, 0.95858246, 0.87365145, 0.54023029,
       0.62838532, 0.3229562 , 0.49159191, 0.89347392, 0.28418017,
       0.60643057, 0.89129257, 0.46362969, 0.56713395, 0.73592

In [39]:
arr_media = np.mean(arr)
arr_media

np.float64(0.498250290438692)

In [45]:
bool_acima_media = arr > arr_media
num_acima_media = np.count_nonzero(bool_acima_media)
num_acima_media

47