In [1]:
import numpy as np

1. Criação e Propriedades de Matrizes
Crie a seguinte matriz 2x3 no NumPy:

A=( 
1
4
​
  
2
5
​
  
3
6
​
 )
Sua tarefa:

Imprima a "forma" (shape) da matriz.

Calcule e imprima a matriz transposta de A.

Acesse e imprima o elemento na segunda linha e terceira coluna (o número 6).

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(f"formato de A: {A.shape}")
print(f"transposta de A:\n {A.T}")
print(f"elemento na seunda linha e terceira coluna: {A[1, 2]}")

formato de A: (2, 3)
transposta de A:
 [[1 4]
 [2 5]
 [3 6]]
elemento na seunda linha e terceira coluna: 6


2. Multiplicação de Matrizes
Dadas as matrizes:

M1=( 
1
3
​
  
2
4
​
 )eM2=( 
5
7
​
  
6
8
​
 )
Sua tarefa:

Calcule o produto matricial M1⋅M2.

Calcule o produto matricial M2⋅M1.

Verifique se os resultados são iguais (a multiplicação de matrizes é comutativa?).

In [14]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])
print(f"produto matricial M1 . M2:\n {M1 @ M2}")
print(f"produto matricial M2 . M2:\n {np.dot(M2, M1)}")
print("Não são comutativas!!!")

produto matricial M1 . M2:
 [[19 22]
 [43 50]]
produto matricial M2 . M2:
 [[23 34]
 [31 46]]
Não são comutativas!!!


3.  Determinante e Matriz Inversa
Dada a matriz:

B=( 
4
2
​
  
7
6
​
 )
Sua tarefa:

Calcule o determinante da matriz B.

Se o determinante for diferente de zero, calcule a matriz inversa de B.

Multiplique B por sua inversa. Qual é o resultado esperado? (Dica: Matriz Identidade)

In [16]:
B = np.array([[4, 7], [2, 6]])
B

array([[4, 7],
       [2, 6]])

In [23]:
print(f'Determinante de B: {np.linalg.det(B):.2f}')
B_inv = np.linalg.inv(B)
print(f'matriz inversa de B:\n {B_inv}')

Determinante de B: 10.00
matriz inversa de B:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [25]:
B @ B_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00]])

5. Problemas Práticos
Exercício 5: Resolvendo um Sistema de Equações Lineares
Imagine que você foi ao mercado. A conta deu o seguinte:

2 maçãs e 3 laranjas custaram R$ 8,00.

4 maçãs e 1 laranja custaram R$ 9,00.

Queremos descobrir o preço de uma maçã (x) e de uma laranja (y). O sistema de equações é:

In [26]:
# matriz de coeficientes
A = np.array([[2, 3], [4, 1]])

# matriz de resultados
B = np.array([8, 7])
precos = np.linalg.solve(A, B)
precos

array([1.3, 1.8])

In [30]:
print(f"Preço maçã: {precos[0]}")
print(f'preço banana: {precos[1]}')

Preço maçã: 1.3
preço banana: 1.8
