In [1]:
import numpy as np

data = np.array([1,2,3])
data

array([1, 2, 3])

In [6]:
# é tranquilo com numpy fazer operações de arrays
dt = np.array([[1,2,3], [4,5,6]])
dt + dt

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
dt * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# os ndarrays são homegeneo, ou seja, só aceitam um tipo de dado
print(dt.shape, dt.dtype)

(2, 3) int64


In [15]:
# criando array:
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4])

In [16]:
# criando array multidimensional
# sempre como se fosse listas aninhadas
data2 = [[5,6,7,8], [9,10,11,12]]
arr2 = np.array(data2)
arr2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# mostrando quantas dimensões tem o array2
arr2.ndim

2

In [18]:
# mostrando o seu formato
arr2.shape

(2, 4)

In [21]:
# funções interessantes como ones, zeros e empty
zero = np.zeros(10) #cria uma array de 10 elementos (0)
print(zero)

um = np.ones((4,5)) #criando uma matriz 4x5 de 1s. quando queremos passar um formato específico, escrevemos em uma tupla (linha,coluna)
print(um)

emp = np.empty((2,3,4)) #criando uma matriz de 3 dimensões vazia
print(emp)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]
  [1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]
  [1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]]

 [[1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]
  [1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]
  [1.07622217e-311 1.07622217e-311 1.07622217e-311 1.07622217e-311]]]


In [28]:
np.asarray(1)


array(1)

In [31]:
# array com sequencia
arr = np.arange(13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
#criar uma matriz identidade com 1 na diagonal e o resto é 0
print(np.eye(5))
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# pode converter o tipo de dado de um ndarray
dt = np.array([1, 2, 3, 4, 5])
print(dt)
print(dt.dtype)

float_dt = dt.astype(np.float64)
print(float_dt)
print(float_dt.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
