In [2]:
import numpy as np

data = np.array([1,2,3])
data

array([1, 2, 3])

In [3]:
# é tranquilo com numpy fazer operações de arrays
dt = np.array([[1,2,3], [4,5,6]])
dt + dt

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
dt * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
# os ndarrays são homegeneos, ou seja, só aceitam um tipo de dado
print(dt.shape, dt.dtype)

(2, 3) int64


In [6]:
# criando array:
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4])

In [7]:
# criando array multidimensional
# sempre como se fosse listas aninhadas
data2 = [[5,6,7,8], [9,10,11,12]]
arr2 = np.array(data2)
arr2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# mostrando quantas dimensões tem o array2
arr2.ndim

2

In [9]:
# mostrando o seu formato
arr2.shape

(2, 4)

In [10]:
# funções interessantes como ones, zeros e empty
zero = np.zeros(10) #cria uma array de 10 elementos (0)
print(zero)

um = np.ones((4,5)) #criando uma matriz 4x5 de 1s. quando queremos passar um formato específico, escrevemos em uma tupla (linha,coluna)
print(um)

emp = np.empty((2,3,4)) #criando uma matriz de 3 dimensões vazia
print(emp)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[4.67296746e-307 1.69121096e-306 9.45755701e-308 7.56587585e-307]
  [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306]
  [7.56601165e-307 1.02359984e-306 1.42417221e-306 7.56593017e-307]]

 [[1.24610587e-306 6.23059726e-307 1.11261027e-306 1.95818994e-306]
  [1.37962456e-306 9.34613864e-307 1.42418172e-306 8.06610918e-308]
  [6.89810244e-307 1.22387550e-307 2.22522596e-306 2.12199579e-312]]]


In [12]:
lista = [1, 2, 3]
arrr = np.asarray(lista) #converte alguma entrada em array
print(arrr)

[1 2 3]


In [31]:
# array com sequencia
arr = np.arange(13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
#criar uma matriz identidade com 1 na diagonal e o resto é 0
print(np.eye(5))
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# pode converter o tipo de dado de um ndarray
dt = np.array([1, 2, 3, 4, 5])
print(dt)
print(dt.dtype)

float_dt = dt.astype(np.float64)
print(float_dt)
print(float_dt.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


### Expressões aritméticas
O numpy permite fazer operações matemáticas de matrizes e vetores sem o uso de do 'for'

In [15]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr * arr)
print(arr + arr)
print(arr - arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### Indexing e Slicing
Manipipulação de array de 1 dimensões são mais tranquilas

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[4]

np.int64(4)

In [19]:
arr[4:8]

array([4, 5, 6, 7])

In [20]:
arr[2] = 123
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

Obs: as manipulações que são feitas no array são vistas no original, ao contrário das listas nativas do python em que uma cópia é feita

In [22]:
arr_slice = arr[8:10]
arr_slice

array([8, 9])

In [23]:
arr_slice[1] = 789
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8, 789])

Para realmente fazer uma cópia:
arr[8:10].copy()

### Slicing e Indexing em um array de 2 dimensões

In [25]:
# dessa forma acessamos apenas as linhas
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1]

array([4, 5, 6])

In [26]:
# acessando um único elemento
arr[0][2] # ou arr[0, 2] (linha, coluna)

np.int64(3)

em arrays multidimensionais, o quão menos específico com o index, mais alta a dimensão 

In [30]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3.shape)
arr3[1]

(2, 2, 3)


array([[ 7,  8,  9],
       [10, 11, 12]])

### Slincing
funciona da mesma forma do indexing

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr[:2] #pecorreu as 2 primeiras linhas do array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

### Indexação booleana

In [38]:
nomes = np.array(["Gui", "Joel", "Rafa", "Gui", "Joel", "Rafa", "Rafa"])
nomes == "Gui"

array([ True, False, False,  True, False, False, False])

In [39]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
data[nomes == "Rafa"]

array([[ -5,   6],
       [-12,  -4],
       [  3,   4]])